env:
  browser: false
  commonjs: true
  es2021: true
extends:
  - airbnb-base
  - prettier
parser: babel-eslint
parserOptions:
  ecmaVersion: 12
rules: { 'prettier/prettier': 'error', 'import/prefer-default-export': 'off' }
